### ISSUE TITLE
Nothing on workflow zip？

### ISSUE THREAD

**Issue by next1foreal** [Wonderflex/WonderflexComfyWorkflows#1]
file is empty，no json

**Comment by Wonderflex** [comment]
Which workflow are you trying out?  I just tested all four workflows currently posted and they contain JSON.  You'll want to open the full size image and then drag it over into ComfyUI.

**Comment by next1foreal** [comment]
Ok, I think I got it. You mean the image contains a JSON file, and I just
need to drag the image into ComfyUI, right? I thought they were just
regular PNG images. Thank you!

Wonderflex ***@***.***> 于 2024年9月21日周六 01:09写道：
